### PR TITLE
The precompilation method (taken from rails assets.rake file) has changed

### PR DESCRIPTION
**Pull request by tomafro**
The precompilation method (taken from rails assets.rake file) has changed in 3.1 final, and the existing guard fails with an error.  This fixes the guard to use the same method in the rake file.  It'd be nice to use the rake file directly, but I found that troublesome.

### CODE REVIEW

**Comment by dnagir** [comment]
There is similar pull request already: https://github.com/dnagir/guard-rails-assets/pull/9

Can you elaborate more why using rake task appears to be troublesome?
It just feels a bit dirty to copy paste stuff from Rails.

You can temporarily use `:runner => :cli` until I'll release. Sorry for delaying it.

**Comment by tomafro** [comment]
I agree that using the code within the rake task would be the best solution; just wanted something quick to keep my current setup working quickly.  I'm running evergreen tests against the generated application.js, so using the cli option increases the write-code/run-tests cycle quite a bit.

I tried quickly getting access to the code in the rake tasks, or running them independently of rake, but it started looking as though the solution would end up being pretty complicated.  There's probably an easier way - I'll look at that other pull request.

**Comment by tomafro** [comment]
Sorry, didn't mean to close it then! Pressed wrong button....

**Comment by thibaudgg** [comment]
Got the same problem with the final Rails 3.1.0 release:

```
Compiling rails assets with Guard::RailsAssets::RailsRunner.
An error occurred compiling assets: undefined method `precompile' for #<Sprockets::Environment:0x007f81ce3cc5b0>
Failed to compile assets.
```

@dnagir fork works well:

```
gem 'guard-rails-assets', :git => 'git://github.com/mcolyer/guard-rails-assets.git', :branch => 'patch-1', :ref => '73d35d98de3b4c1f510ed666f9a16c869c2567c6'
```

**Comment by tomafro** [comment]
Other branch works for me too, so closing this issue.

**Comment by cmeiklejohn** [comment]
`:runner => :cli` is not working for me, however @dnagir's fork is working as suggested by @thibaudgg.

**Pull request closed without merging**
