### PR TITLE
Moving version.rb into package directory

### PR DESCRIPTION
**Pull request by kassi**
This commit is necessary to avoid errors when using this gem together with other guard gems like guard-rake.
The error you get is e.g.:
    uninitialized constant Guard::VERSION
because guard/version is already loaded (from your package), not defining Guard::VERSION

### CODE REVIEW

**Comment by dnagir** [comment]
@kassi thanks for the PR.

Unfortunately I don't have to maintain it now (I reckon this guard is relatively obsolete and there are better tools to use with rails).

Also it looks like this PR will break the gemspec: https://github.com/dnagir/guard-rails-assets/blob/master/guard-rails-assets.gemspec#L3

Maybe @thibaudgg from @guard wants to take over?

**Comment by thibaudgg** [comment]
Hi @dnagir, I don't use guard-rails-assets either. Maybe you could tell to @kassi which are the better tools to use? Thanks!

**Comment by kassi** [comment]
Hi,
Never mind.
I just tried this gem finding a way to generate sprites from images with compass when they change. Since we want to commit them to the repo I wanted guard to do the work instead of having to do a page request.
Then I found the problem.
I'm not using it now. Unfortunately guard-rake doesn't work with the task assets:precompile (maybe I should open an issue there) so that I temporarily switched to guard-shell, which is ugly because time consuming and also I would have to add another rake task as a shell command later.

Thanks!

**Comment by dnagir** [comment]
@kassi you are doing something wrong mate :)

guard-rails-assets was supposed to be used for testing.

Since Rails 3 I personally replaced it with https://github.com/bradphelan/jasminerice and guard-jasmine.

**Comment by kassi** [comment]
Ok, got it. I thought it would also be helpful in creating stuff. However, as mentioned, I'm not using it anymore.
Let's see how we can get guard-rake running :-)

**Pull request closed without merging**
