### PR TITLE
Update to Rails 3.1rc6 and Sprockets 2.0rc15

### PR DESCRIPTION
**Pull request by mcolyer**
Since the asset pipeline seems to be a fairly rapidly moving target I've update the code in the rails runner so that it continues to work with the latest and greatest.

### CODE REVIEW

**Comment by dnagir** [comment]
Thanks. I will merge and release it when I'll be in my dev environment.

**Comment by mcolyer** [comment]
I looked at this some more and it is wrapped in a function we can't use externally from https://github.com/rails/rails/blob/master/actionpack/lib/sprockets/assets.rake

As far as I can tell the only thing that changed is that the rails internal api got more complicated and it's not that we are copying any more than previously.

**Comment by dnagir** [comment]
Maybe we should just change all that to simply run the rake task?

**Comment by mcolyer** [comment]
The rake task invokes the application initializer task (which is the slow
part). Will it continue to execute if you keep calling invoke on it?

**Comment by dnagir** [comment]
Not sure. Need to play with it.

**Comment by mcolyer** [comment]
Also I found a way to eliminate the annoying md5 hashes, so now the filename is predictable each time.

**Comment by dnagir** [comment]
Did you figure out if it is possible to use Rake tasks instead of re-implementing Sproackets/Rails parts?

**Comment by dnagir** [comment]
I would rather prefer to use Rake task from Rails. It is the safest way.
Not sure whether it is possible though.

**Comment by dnagir** [comment]
Hi Guys,

I tried to use Rails Rake tasks and it seems to be possible. But there are following issues that I'm not sure how to fix:
1. Rails reloads all the classes (including Guard itself) which is a killing side effect. This means the class variable `@@rails_booted` is reset every time.
2. It looks like Sprockets caches all the files so when you save it, the content is not recompiled.

The 2nd one could probably be fixed by [`cache = nil`](https://github.com/dnagir/guard-rails-assets/blob/issue9/lib/guard/rails-assets/rails_runner.rb#L18).
I am not sure how to deal with the 1st though.

I left all the `puts` for you to see what's happening.

So what we need to do is to:
1. Make sure rails is loaded only once and no classes get reloaded.
2. Make sure no caching of assets is happening.

Would appreciate your help in my branch [issue9](https://github.com/dnagir/guard-rails-assets/blob/issue9/lib/guard/rails-assets/rails_runner.rb)

**Comment by thibaudgg** [comment]
With branch issue9 I got this error on Guard start:

```

Compiling rails assets with Guard::RailsAssets::RailsRunner.
------------BOOTING RAILS
--- CACHE=#<ActiveSupport::Cache::FileStore:0x007fb83e4001c0>
ERROR: Guard::RailsAssets failed to achieve its <start>, exception was:
NoMethodError: undefined method `application' for Rake:Module
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/rake-0.9.2/lib/rake/dsl_definition.rb:95:in `namespace'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/railties/databases.rake:3:in `<top (required)>'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `load'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `block in load'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `block in load_dependency'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in `new_constants_in'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `load'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/railtie.rb:26:in `block in <class:Railtie>'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/railties-3.1.0/lib/rails/railtie.rb:183:in `call'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/railties-3.1.0/lib/rails/railtie.rb:183:in `block in load_tasks'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/railties-3.1.0/lib/rails/railtie.rb:183:in `each'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/railties-3.1.0/lib/rails/railtie.rb:183:in `load_tasks'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/railties-3.1.0/lib/rails/engine.rb:395:in `block in load_tasks'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/railties-3.1.0/lib/rails/application/railties.rb:8:in `each'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/railties-3.1.0/lib/rails/application/railties.rb:8:in `all'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/railties-3.1.0/lib/rails/engine.rb:395:in `load_tasks'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/railties-3.1.0/lib/rails/application.rb:99:in `load_tasks'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/bundler/gems/guard-rails-assets-733f8642f182/lib/guard/rails-assets/rails_runner.rb:19:in `boot_rails'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/bundler/gems/guard-rails-assets-733f8642f182/lib/guard/rails-assets/rails_runner.rb:29:in `compile_assets'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/bundler/gems/guard-rails-assets-733f8642f182/lib/guard/rails-assets.rb:33:in `compile_assets'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/bundler/gems/guard-rails-assets-733f8642f182/lib/guard/rails-assets.rb:15:in `start'
/Users/Thibaud/Codes/guard/lib/guard.rb:104:in `supervised_task'
/Users/Thibaud/Codes/guard/lib/guard.rb:41:in `block in start'
/Users/Thibaud/Codes/guard/lib/guard.rb:41:in `each'
/Users/Thibaud/Codes/guard/lib/guard.rb:41:in `start'
/Users/Thibaud/Codes/guard/lib/guard/cli.rb:17:in `start'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
/Users/Thibaud/Codes/guard/bin/guard:6:in `<top (required)>'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/bin/guard:19:in `load'
/Users/Thibaud/Codes/test/vendor/ruby/1.9.1/bin/guard:19:in `<main>'

Guard::RailsAssets has just been fired
```

**Comment by dnagir** [comment]
That's strange. Here is what I get (Note how Guard and Rails loads twice):

```
Guard is now watching at '/home/dima/proj/tmp/ha'
Compiling rails assets with Guard::RailsAssets::RailsRunner.
------------BOOTING RAILS
--- CACHE=#<ActiveSupport::Cache::FileStore:0x000000059fa5d8>
-- BOOTED after?=true
Guard is now watching at '/home/dima/proj/tmp/ha'
Compiling rails assets with Guard::RailsAssets::RailsRunner.
------------BOOTING RAILS
--- CACHE=#<ActiveSupport::Cache::FileStore:0x0000000449c6f0>
ERROR: Guard::RailsAssets failed to achieve its <start>, exception was:
TypeError: can't modify immutable index
/home/dima/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.0/lib/sprockets/index.rb:59:in `expire_index!'
/home/dima/.rvm/gems/ruby-1.9.2-p290/gems/sprockets-2.0.0/lib/sprockets/base.rb:40:in `cache='
/home/dima/proj/guard-rails-assets/lib/guard/rails-assets/rails_runner.rb:19:in `boot_rails'
/home/dima/proj/guard-rails-assets/lib/guard/rails-assets/rails_runner.rb:30:in `compile_assets'
/home/dima/proj/guard-rails-assets/lib/guard/rails-assets.rb:33:in `compile_assets'
/home/dima/proj/guard-rails-assets/lib/guard/rails-assets.rb:15:in `start'
/home/dima/.rvm/gems/ruby-1.9.2-p290/gems/guard-0.6.3/lib/guard.rb:66:in `supervised_task'
```

I have [required](https://github.com/dnagir/guard-rails-assets/commit/c69f31008fd54d6f08217724c9d4b0c6139ed0ea) rake which might fix it. Can you give it a shot?

**Comment by thibaudgg** [comment]
Are you using Rake 0.9.2?

**Comment by dnagir** [comment]
yes.

**Comment by thibaudgg** [comment]
And you're launching guard with `bundle exec` ? (just to be sure :))

**Comment by dnagir** [comment]
yes. to be precise: `bundle exec guard -g front` if that matters.

**Comment by dnagir** [comment]
I figured it all out.
It is a bit hacky, but should work with Rails now.
Please update to the new version `0.0.7`.

There is also additional option available now: `:rails_env`.

**Comment by dnagir** [comment]
@carhartl, @tomafro FYI. Version `0.0.7` is compatible with Rails 3.1 final.

**Comment by carhartl** [comment]
Thanks!

**Comment by thibaudgg** [comment]
Works great, thanks!

**Pull request merged**
