### PR TITLE
Patch to keep rails loaded in a background thread

### PR DESCRIPTION
**Pull request by stevehodgkiss**
Compilation is much faster now.

### CODE REVIEW

**Comment by stevehodgkiss** [comment]
Actually, since loading code isn't thread specific, it's probably a better idea to use fork or spork...

**Comment by dnagir** [comment]
Thanks for the patch. I agree that it's better to use spork.

Also there was a discussion (https://github.com/jamesarosen/guard-rails-assets/commit/8424beee1e624e0835e28a946ac4664612839337#comments) re whether to use custom compilation/cleanup and we decided it's better to use the Rails rake tasks to do the compilation.

So I guess better way of doing it would be to run the Rails rake tasks but through spork.

Did you close the pull request because loading Rails caused some conflicts?

**Comment by stevehodgkiss** [comment]
I closed the patch because the threading stuff I did was unnecessary. Currently I have it loading the rails app in the guard ruby process, which works fine except to reload rails you have to restart guard manually. To be able to reload rails cleanly we'd need to use spork/fork. The main problem is solved though (speed/not having to reload rails for every change).

https://github.com/stevehodgkiss/guard-rails-assets/commit/431daf19a0f0a90227bb9d27f2f6c11cc40a459e

**Comment by dnagir** [comment]
Loading Rails into Guard might cause some issues, especially with existing gems.

The main question for me is how conflicts are resolved for gems that are used in other guards and Rails' gems (Gemfile)?

It would be a shame if the conflicts would prohibit using the guard.

On the other side, if we always run `bundle exec guard`, then it should not be a problem.
So if you think there is no problem, then send the pull request and I'll merge it in a bit later.

**Pull request closed without merging**
